- name: Example credential plugin use
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: Print credentials
      debug:
        msg:
          - "{{ Username = lookup('env', 'USERNAME') }}"
          - "{{ Password = lookup('env', 'PASSWORD') }}"
